# Change these first
owner: Metro-Transit-Industries # Your GitHub organization or username, where this repository lives
repo: Status-Page # The name of this repository

sites:
  - name: Main Website
    url: https://metrotransitindustries.com
  - name: MTI Hub
    url: https://metrotransitindustries.com/hub
  - name: MTI Admin
    url: https://metrotransitindustries.com/admin

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.metrotransitindustries.com
  # baseUrl: /your-repo-name
  logoUrl: https://metrotransitindustries.com/assets/logos/big.webp
  name: Upptime
  introTitle: "**Metro Transit Status*"
  introMessage: This is the Metro Transit Industries status page, showing the status and uptime of all MTI services, including websites and Discord bots.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://metrotransitindustries.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
